import { rm } from 'fs/promises';
import path from 'path';
import { UPLOADS_DIR, THUMBS_DIRNAME } from './env';

// Every image this app accepts, keyed by the format name sharp reports. The
// extension and content type both come from this table rather than from
// anything the client sent, which is what makes the set closed: a file can only
// ever be stored and served as one of these five.
export const ALLOWED_FORMATS: Record<string, { ext: string; mime: string }> = {
  jpeg: { ext: '.jpg', mime: 'image/jpeg' },
  png: { ext: '.png', mime: 'image/png' },
  gif: { ext: '.gif', mime: 'image/gif' },
  webp: { ext: '.webp', mime: 'image/webp' },
  avif: { ext: '.avif', mime: 'image/avif' },
};

const MIME_BY_EXT: Record<string, string> = Object.fromEntries(
  Object.values(ALLOWED_FORMATS).map(({ ext, mime }) => [ext, mime])
);

export function contentTypeFor(relative: string): string | null {
  return MIME_BY_EXT[path.extname(relative).toLowerCase()] ?? null;
}

// Filenames are generated by the upload route, so they should always be safe.
// This still resolves and range-checks them: a single bad row must not be able
// to point rm() — or the file reader — at something outside the uploads root.
export function resolveInsideUploads(relative: string): string | null {
  // Reject before resolving as well as after. path.resolve() collapses `..`,
  // so a traversal that lands back inside the root would otherwise pass the
  // prefix check while still not being a name this app ever generated.
  if (path.isAbsolute(relative) || relative.split(/[\\/]/).includes('..')) {
    return null;
  }

  const resolved = path.resolve(UPLOADS_DIR, relative);
  const root = path.resolve(UPLOADS_DIR) + path.sep;

  return resolved.startsWith(root) ? resolved : null;
}

export function thumbRelativePath(name: string): string {
  return `${THUMBS_DIRNAME}/${name}`;
}

// Best-effort by design, and always called *after* the database rows are gone.
// A leftover blob on disk is invisible; a surviving row whose file was unlinked
// renders as a broken tile. Nulls are accepted so callers can pass
// `thumbFilename` straight through — it is nullable for photos that predate
// thumbnails.
export async function removeUploadFiles(names: (string | null | undefined)[]): Promise<void> {
  const targets = names
    .filter((name): name is string => !!name)
    .map(resolveInsideUploads)
    .filter((target): target is string => !!target);

  for (const target of targets) {
    try {
      await rm(target, { force: true }); // force: already-missing files are fine
    } catch (fileError) {
      console.error('Failed to remove upload file:', target, fileError);
    }
  }
}
