import { rm } from 'fs/promises';
import path from 'path';

const uploadsDir = path.join(process.cwd(), 'public', 'uploads');

// Filenames are generated by the upload route, so they should always be safe.
// This still resolves and range-checks them: a single bad row must not be able
// to point rm() at something outside public/uploads.
function resolveInsideUploads(relative: string): string | null {
  const resolved = path.resolve(uploadsDir, relative);
  const root = path.resolve(uploadsDir) + path.sep;
  return resolved.startsWith(root) ? resolved : null;
}

// Best-effort by design, and always called *after* the database rows are gone.
// A leftover blob on disk is invisible; a surviving row whose file was unlinked
// renders as a broken tile. Nulls are accepted so callers can pass
// `thumbFilename` straight through — it is nullable for photos that predate
// thumbnails.
export async function removeUploadFiles(names: (string | null | undefined)[]): Promise<void> {
  const targets = names
    .filter((name): name is string => !!name)
    .map(resolveInsideUploads)
    .filter((target): target is string => !!target);

  for (const target of targets) {
    try {
      await rm(target, { force: true }); // force: already-missing files are fine
    } catch (fileError) {
      console.error('Failed to remove upload file:', target, fileError);
    }
  }
}
